# 大文字と小文字を区別するため注意して定義してください
# ------------------------------------------------------------
# Issuesテーブルの拡張フィールド用定義
# key:カラム名 value:XML内から要素取得のためのXpath
# ------------------------------------------------------------
issue_extras: 
# 運用種別(Status)
 "xml_control_status": "/Report/Control/Status/text()"
# 編集官署名(EditorialOffice)
 "xml_control_editorialoffice": "/Report/Control/EditorialOffice/text()"
# 発表官署名(PublishingOffice)
 "xml_control_publishingoffice": "/Report/Control/PublishingOffice/text()"
# 標題(Title)
 "xml_head_title": "/Report/Head/Title/text()"
# 題名(Title)
 "subject": "/Report/Head/Title/text()"
# 発表時刻(ReportDateTime)
 "xml_head_reportdatetime": "/Report/Head/ReportDateTime/text()"
# 基点時刻(TargetDateTime)
 "xml_head_targetdatetime": "/Report/Head/TargetDateTime/text()"
# 基点時刻のあいまいさ(TargetDTDubious)
 "xml_head_targetdtdubious": "/Report/Head/TargetDTDubious/text()"
# 基点時刻からとりうる時間(TargetDuration)
 "xml_head_targetsuration": "/Report/Head/TargetDuration/text()"
# 失効時刻(ValidDateTime)
 "xml_head_validdatetime": "/Report/Head/ValidDateTime/text()"
# 識別情報(EventID)
 "xml_head_eventid": "/Report/Head/EventID/text()"
# 情報形態(InfoType)
 "xml_head_infotype": "/Report/Head/InfoType/text()"
# 情報番号(Serial)
 "xml_head_serial": "/Report/Head/Serial/text()"
# スキーマの運用種別情報(InfoKind)
 "xml_head_infokind": "/Report/Head/InfoKind/text()"
# スキーマの運用種別情報バージョン(InfoKindVersion)
 "xml_head_infokindversion": "/Report/Head/InfoKindVersion/text()"
# 見出し文(Text)
 "xml_head_text": "/Report/Head/Headline/Text/text()"


# ------------------------------------------------------------
# Issues_addition_datumテーブルに保存する位置系データ取得用定義
# coordinate,line,polygon,Locationの種類毎にXpathを複数定義可能
# 指定したXpathで取得できたものを全てissues_addtion_datumテーブルに格納する
# valid_coordinate_typesにはCoordinate要素のtype属性名を指定
# ここに指定されているtypeの場合のみデータを取得する
# coordinateは上記のようにtypeによる判定が必要なため/Text()を含まない
# Xpathを定義する。type属性による判定をロジックで行うため。
# ------------------------------------------------------------
issue_geographys: 
 "coordinate": 
  - # 全般海上警報
   basePath: "/Repot/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Area/"
   relativePath: "Coordinate/text()"
   remarksPaths: ["Name/text()", "/@type"]
  - # 台風解析・予報情報, 全般海上警報, 地上実況図, 地上予想図
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Area/"
   relativePath: "Circle/BasePoint/Coordinate/text()"
   remarksPaths: ["Name/text()", "/@type"]
  - # 紫外線観測データ
   basePath: "/Report/Body/MeteorologicalInfos/TimeSeriesInfo/Item/Station/"
   relativePath: "Coordinate/text()"
   remarksPaths: ["Name/text()"]
  - # 台風解析・予報情報, 全般海上警報, 地上実況図, 地上予想図
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/"
   relativePath: "CenterPart/Coordinate/text()"
   remarksPaths: ["Coordinate/Type/text()"]
  - # 全般海上警報
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/"
   relativePath: "CenterPart/ProbabilityCircle/Circle/BasePoint/Coordinate/text()"
   remarksPaths: ["Coordinate/Type/text()"]
  - # 台風解析・予報情報, 全般海上警報
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/CoordinatePart/"
   relativePath: "Coordinate/text()"
   remarksPaths: ["Type/text()"]
  - # 台風解析・予報情報, 全般海上警報
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/"
   relativePath: "WarningAreaPart/Circle/BasePoint/Coordinate/text()"
   remarksPaths: ["Coordinate/Type/text()"]
  - # 地震関連, 津波関連
   basePath: "/Report/Body/Earthquake/Hypocenter/Area/HypoArea/Coordinate/"
   relativePath: "text()"
   static_remarks: "震源位置"
  - # 噴火関連
   basePath: "/Report/Body/VolcanoInfo/Item/Areas/Area/"
   relativePath: "Coordinate/Coordinate/text()"
   remarksPaths: ["Area/Name/text()"]
  - # 噴火関連
   basePath: "/Report/Body/VolcanoInfo/Item/Areas/Area/CraterCoordinate/Coordinate/"
   relativePath: "text()"
   static_remarks: "火口の位置"
 "line": 
  - # 全般海上警報
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/"
   relativePath: "Area/Line/text()"
   remarksPaths: ["Kind/Name/text()"]
  - # 全般海上警報
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/"
   relativePath: "Kind/Property/CoordinatePart/Line/text()"
   remarksPaths: ["Kind/Name/text()"]
  - # 地上実況図, 地上予想図
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/"
   relativePath: "Kind/Property/IsobarPart/Line/text()"
   remarksPaths: ["Kind/Name/text()"]
 "polygon": 
  - # 全般海上警報
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/"
   relativePath: "Area/Polygon/text()"
   remarksPaths: ["Kind/Name/text()"]
  - # 全般海上警報
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/"
   relativePath: "Kind/Property/CoordinatePart/Polygon/text()"
   remarksPaths: ["Kind/Name/text()"]
  - # 地上予想図, 地上実況図
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/"
   relativePath: "Kind/Property/IsobarPart/Polygon/text()"
   remarksPaths: ["Kind/Name/text()"]
 "Location": 
  - # 特殊気象報
   basePath: "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/"
   relativePath: "Kind/Property/IsobarPart/Polygon/text()"
   remarksPaths: ["Kind/Name/text()"]
  - # 紫外線観測データ
   basePath: "/Report/Body/MeteorologicalInfos/TimeSeriesInfo/Item/Station/"
   relativePath: "Location/text()"
   remarksPaths: ["Name/text()"]
  - # 指定河川洪水予報
   basePath: "/Report/Body/Waring/Item/Stations/Station/"
   relativePath: "Location/text()"
   remarksPaths: ["Name/text()"]
  - # 指定河川洪水予報
   basePath: "/Report/Body/AdditionalInfo/FloodForecastAddition/HydrometricStationPart/Area/"
   relativePath: "Location/text()"
   remarksPaths: ["Name/text()"]
 "valid_coordinate_types": ["観測所の位置", "中心位置（度）", "実況位置（度）", "１２時間後位置（度）", "２４時間後位置（度）", "位置（度）", "予想位置　１２時間後（度）", "予想位置　２４時間後（度）", "中心位置（度）", "震源位置（度）", "火山の位置", "火口の位置"]


# ------------------------------------------------------------
# カスタムフィールド用定義
# key:カスタムフィールドID value:XML内から要素取得のためのXpath
# ------------------------------------------------------------
custom_fields: 


# ------------------------------------------------------------
# トラッカー用定義
# Path: トラッカー判別用テキスト取得のためのXpath
# Type: トラッカーID定義
# ここに定義のないtypeに関しては全て"気象情報（警報・注意報）"トラッカーID:4を使用する
# ------------------------------------------------------------
trackers: 
 path: "/Report/Control/Title/text()"
 type: 
  "季節観測": "4"
  "生物季節観測": "4"
  "特殊気象報": "4"
  "紫外線観測データ": "4"
  "全般台風情報": "4"
  "全般台風情報（定型）": "4"
  "全般台風情報（詳細）": "4"
  "台風解析・予報情報（３日予報）": "3"
  "台風解析・予報情報（５日予報）": "3"
  "全般海上警報（定時）": "4"
  "全般海上警報（臨時）": "4"
  "地方海上警報": "4"
  "地方海上予報": "4"
  "気象警報・注意報": "3"
  "指定河川洪水予報": "3"
  "記録的短時間大雨情報": "4"
  "竜巻注意情報": "3"
  "全般気象情報": "4"
  "地方気象情報": "4"
  "府県気象情報": "4"
  "府県天気概況": "4"
  "府県天気予報": "4"
  "全般週間天気予報": "4"
  "地方週間天気予報": "4"
  "府県週間天気予報": "4"
  "スモッグ気象情報": "4"
  "地方天候情報": "4"
  "震源に関する情報": "3"
  "震源・震度に関する情報": "3"
  "震度速報": "3"
  "地震の活動状況等に関する情報": "4"
  "地震回数に関する情報": "4"
  "顕著な地震の震源要素更新のお知らせ": "3"
  "津波警報・注意報・予報": "3"
  "津波警報・注意報・予報a": "3"
  "緊急地震速報（予報）": "3"
  "緊急地震速報（警報）": "3"
  "東海地震観測情報": "4"
  "東海地震注意情報": "4"
  "東海地震予知情報": "4"
  "地震・津波に関するお知らせ": "4"
  "火山に関するお知らせ": "4"
  "噴火警報・予報": "4"
  "火山の状況に関する解説情報": "4"
  "噴火に関する火山観測報": "4"
  "火山現象に関する海上警報・海上予報": "4"
  "府県海氷予報": "4"
  "全般潮位情報": "4"
  "地方潮位情報": "4"
  "府県潮位情報": "4"
  "緊急地震速報配信テスト": "4"
  "全般スモッグ気象情報": "4"
  "地方高温注意情報": "4"
  "府県高温注意情報": "4"
  "地上実況図": "4"
  "地上２４時間予想図": "4"
  "地上４８時間予想図": "4"
  "沖合の津波観測に関する情報": "4"
  "全般天候情報": "4"
  "府県天候情報": "4"
  "全般１か月予報": "4"
  "全般３か月予報": "4"
  "全般暖・寒候期予報": "4"
  "地方１か月予報": "4"
  "地方３か月予報": "4"
  "地方暖・寒候期予報": "4"
  "異常天候早期警戒情報": "4"


# ------------------------------------------------------------
# プロジェクト用定義
# key: 各種プロジェクト識別子 value: プロジェクトID
# jma -> JMA受信用プロジェクト
# kasen -> 河川受信用プロジェクト
# training -> 災害訓練用プロジェクト
# test -> 通信テスト用プロジェクト
# ------------------------------------------------------------
projects: 
 path: "/Report/Control/Status/text()"
 type: 
  "通常": "jma-project"
  "訓練": "training-project"
  "試験": "test-project"
  "default": "jma-project"


# ------------------------------------------------------------
# プロジェクト自動立ち上げ/自動配信用の定義
# targetsにはLGDISのdestination_list.ymlに設定されている
# 配信先IDをリストで指定
# 1: 公共情報コモンズ
# 2: 自治体職員向けメール
# 3: まちcomi向けメール
# 4: Twitter
# 5: Facebook
# ------------------------------------------------------------
auto: 
 earthquake_path: "/Report/Body/Earthquake/Magnitude/text()"
 tsunami_path: "/Report/Body/Tsunami/Forecast/Item/MaxHeight/TsunamiHeight/text()"
 launch: 
  earthquake_threashold: 5.5
  tsunami_threashold: 1.7
 send: 
  earthquake_threashold: 7.5
  tsunami_threashold: 1.7
  targets: ["2", "3", "4", "5"]
