# 大文字と小文字を区別するため注意して定義してください
# ------------------------------------------------------------
# カスタムフィールド用定義
# key:カスタムフィールドID value:XML内から要素取得のためのXpath
# ------------------------------------------------------------
custom_fields: 
# 運用種別(Status)
# "": "/Report/Control/Status/text()"
# 編集官署名(EditorialOffice)
# "": "/Report/Control/EditorialOffice/text()"
# 発表官署名(PublishingOffice)
 "22": "/Report/Control/PublishingOffice/text()"
# 発表時刻(ReportDateTime)
# "": "/Report/Head/ReportDateTime/text()"
# 基点時刻(TargetDateTime)
# "": "/Report/Head/TargetDateTime/text()"
# 基点時刻のあいまいさ(TargetDTDubious)
# "": "/Report/Head/TargetDTDubious/text()"
# 予報期間(TargetDuration)
# "": "/Report/Head/TargetDuration/text()"
# 失効時刻(ValidDateTime)
# "": "/Report/Head/ValidDateTime/text()"
# 識別情報(EventID)
# "": "/Report/Head/EventID/text()"
# 情報形態(InfoType)
# "": "/Report/Head/InfoType/text()"
# 情報番号(Serial)
# "": "/Report/Head/Serial/text()"
# スキーマの運用種別情報(InfoKind)
# "": "/Report/Head/InfoKind/text()"
# スキーマの運用種別情報バージョン(InfoKindVersion)
# "": "/Report/Head/InfoKindVersion/text()"
# 見出し文(Text)
 "4": "/Report/Head/Headline/Text/text()"


# ------------------------------------------------------------
# トラッカー用定義
# Path: Information type 取得のためのXpath
# Type: Information type 毎のトラッカーID定義
# ------------------------------------------------------------
trackers: 
 path: "/Report/Head/Headline/Information/@type"
 type: 
  "緊急地震速報（地方予報区）": "1"
  "津波予報領域表現": "2"


# ------------------------------------------------------------
# プロジェクト用定義
# key: 各種プロジェクト識別子 value: プロジェクトID
# jma -> JMA受信用プロジェクト
# kasen -> 河川受信用プロジェクト
# training -> 災害訓練用プロジェクト
# test -> 通信テスト用プロジェクト
# ------------------------------------------------------------
projects: 
 path: "/Report/Control/Status/text()"
 type: 
  "通常": "rms-project"
  "訓練": "rms-project"
  "試験": "test-project"
  "default": "rms-project"


# ------------------------------------------------------------
# プロジェクト自動立ち上げ/自動配信用の定義
# targetsにはLGDISのdestination_list.ymlに設定されている
# 配信先IDをリストで指定
# 1: 公共情報コモンズ
# 2: 自治体職員向けメール
# 3: まちcomi向けメール
# 4: Twitter
# 5: Facebook
# ------------------------------------------------------------
auto: 
 earthquake_path: "/Report/Body/Earthquake/Magnitude/text()"
 tsunami_path: "/Report/Body/Tsunami/Forecast/Item/MaxHeight/TsunamiHeight/text()"
 launch: 
  earthquake_threashold: 7.1
  tsunami_threashold: 2.7
 send: 
  earthquake_threashold: 7.0
  tsunami_threashold: 2.5
  targets: ["2", "3", "4", "5"]
