# 大文字と小文字を区別するため注意して定義してください
# ------------------------------------------------------------
# Issuesテーブルの拡張フィールド用定義
# key:カラム名 value:XML内から要素取得のためのXpath
# ------------------------------------------------------------
issue_extras: 
# 運用種別(Status)
 "xml_control_status": "/Report/Control/Status/text()"
# 編集官署名(EditorialOffice)
 "xml_control_editorialoffice": "/Report/Control/EditorialOffice/text()"
# 発表官署名(PublishingOffice)
 "xml_control_publishingoffice": "/Report/Control/PublishingOffice/text()"
# 標題
 "xml_head_title": "/Report/Head/Title/text()"
# 題名
 "subject": "/Report/Head/Title/text()"
# 発表時刻(ReportDateTime)
 "xml_head_reportdatetime": "/Report/Head/ReportDateTime/text()"
# 基点時刻(TargetDateTime)
 "xml_head_targetdatetime": "/Report/Head/TargetDateTime/text()"
# 基点時刻のあいまいさ(TargetDTDubious)
 "xml_head_targetdtdubious": "/Report/Head/TargetDTDubious/text()"
# 基点時刻からとりうる時間(TargetDuration)
 "xml_head_targetsuration": "/Report/Head/TargetDuration/text()"
# 失効時刻(ValidDateTime)
 "xml_head_validdatetime": "/Report/Head/ValidDateTime/text()"
# 識別情報(EventID)
 "xml_head_eventid": "/Report/Head/EventID/text()"
# 情報形態(InfoType)
 "xml_head_infotype": "/Report/Head/InfoType/text()"
# 情報番号(Serial)
 "xml_head_serial": "/Report/Head/Serial/text()"
# スキーマの運用種別情報(InfoKind)
 "xml_head_infokind": "/Report/Head/InfoKind/text()"
# スキーマの運用種別情報バージョン(InfoKindVersion)
 "xml_head_infokindversion": "/Report/Head/InfoKindVersion/text()"
# 見出し文(Text)
 "xml_head_text": "/Report/Head/Headline/Text/text()"


# ------------------------------------------------------------
# Issues_addition_datumテーブルのフィールド用定義
# key:カスタムフィールドID value:XML内から要素取得のためのXpath
# ------------------------------------------------------------
issue_addition_datums: 
 "coordinate": 
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Area/Coordinate"
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Area/Circle/BasePoint/Coordinate"
  - "/Report/Body/MeteorologicalInfos/TimeSeriesInfo/Item/Station/Coordinate"
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/CenterPart/Coordinate"
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/CoordinatePart/Coordinate"
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/CenterPart/ProbabilityCircle/Circle/BasePoint/Coordinate"
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/WarningAreaPart/Circle/BasePoint/Coordinate"
  - "/Report/Body/Earthquake/Hypocenter/Area/HypoArea/Coordinate"
  - "/Report/Body/VolcanoInfo/Item/Areas/Area/Coordinate/Coordinate"
  - "/Report/Body/VolcanoInfo/Item/Areas/Area/CraterCoordinate/Coordinate"
 "line": 
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Area/Line/text()"
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/CoordinatePart/Line/text()"
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/IsobarPart/Line/text()"
 "polygon": 
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Area/Polygon/text()"
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/CoordinatePart/Polygon/text()"
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Kind/Property/IsobarPart/Polygon/text()"
 "Location": 
  - "/Report/Body/MeteorologicalInfos/MeteorologicalInfo/Item/Station/Location/text()"
  - "/Report/Body/MeteorologicalInfos/TimeSeriesInfo/Item/Station/Location/text()"
  - "/Report/Body/Waring/Item/Stations/Station/Location/text()"
  - "/Report/Body/Waring/Item/Stations/Station/Location/text()"
  - "/Report/Body/AdditionalInfo/FloodForecastAddition/HydrometricStationPart/Area/Location/text()"
 "valid_coordinate_types": ["観測所の位置", "中心位置（度）", "実況位置（度）", "１２時間後位置（度）", "２４時間後位置（度）", "位置（度）", "予想位置　１２時間後（度）", "予想位置　２４時間後（度）", "中心位置（度）", "震源位置（度）", "火山の位置", "火口の位置"]


# ------------------------------------------------------------
# カスタムフィールド用定義
# key:カスタムフィールドID value:XML内から要素取得のためのXpath
# ------------------------------------------------------------
custom_fields: 


# ------------------------------------------------------------
# トラッカー用定義
# Path: Information type 取得のためのXpath
# Type: Information type 毎のトラッカーID定義
# ------------------------------------------------------------
trackers: 
 path: "/Report/Head/Headline/Information/@type"
 type: 
  "緊急地震速報（地方予報区）": "4"
  "津波予報領域表現": "4"
  "震度速報": "4"
  "噴火警報・予報（対象火山）": "4"
  "気象警報・注意報（府県予報区等）": "4"


# ------------------------------------------------------------
# プロジェクト用定義
# key: 各種プロジェクト識別子 value: プロジェクトID
# jma -> JMA受信用プロジェクト
# kasen -> 河川受信用プロジェクト
# training -> 災害訓練用プロジェクト
# test -> 通信テスト用プロジェクト
# ------------------------------------------------------------
projects: 
 path: "/Report/Control/Status/text()"
 type: 
  "通常": "jma-project"
  "訓練": "training-project"
  "試験": "test-project"
  "default": "jma-project"


# ------------------------------------------------------------
# プロジェクト自動立ち上げ/自動配信用の定義
# targetsにはLGDISのdestination_list.ymlに設定されている
# 配信先IDをリストで指定
# 1: 公共情報コモンズ
# 2: 自治体職員向けメール
# 3: まちcomi向けメール
# 4: Twitter
# 5: Facebook
# ------------------------------------------------------------
auto: 
 earthquake_path: "/Report/Body/Earthquake/Magnitude/text()"
 tsunami_path: "/Report/Body/Tsunami/Forecast/Item/MaxHeight/TsunamiHeight/text()"
 launch: 
  earthquake_threashold: 7.5
  tsunami_threashold: 1.7
 send: 
  earthquake_threashold: 7.5
  tsunami_threashold: 1.7
  targets: ["2", "3", "4", "5"]
