# ------------------------------------------------------------
# Redmineにrest要求するための各種定義
# ------------------------------------------------------------
redmine: 
 protocol: "http"
 target_host: "203.138.187.88"
# target_port: "3000"   # ポート番号を指定する場合のみ使用する
 issues_post_api: "/redmine/issues.xml?format=xml"
 uploads_post_api: "/redmine/uploads.xml?format=xml"
 issues_post_content_type: "text/xml; charset=UTF-8"
 uploads_post_content_type: "application/octet-stream"
 api_key: "871cbf8868511fea61f06d09383b612d2fbbb4b7"
 timeout: 120000
 retry_count: 5
 basicauth_id: test
 basicauth_password: 1qazxsw2


# ------------------------------------------------------------
# PDFファイルをチケット登録する際の固定情報
# key:restのパラメータ名 value:設定する値
# ------------------------------------------------------------
pdf_attachment_statics: 
 subject: "PDFファイル"
 project_id: "jma-project"
 tracker_id: "4"
 filename: "jma.pdf"
 description: "This is pdf file."
 content_type: "application/pdf"


# ------------------------------------------------------------
# テキストファイルをチケット登録する際の固定情報
# key:restのパラメータ名 value:設定する値
# ------------------------------------------------------------
text_attachment_statics: 
 subject: "JMA"
 project_id: "jma-project"
 tracker_id: "4"
 filename: "jma.txt"
 description: "This is text file."
 content_type: "text/plain"


# ------------------------------------------------------------
# テキストファイルをチケット登録する際の固定情報
# key:restのパラメータ名 value:設定する値
# ------------------------------------------------------------
tar_attachment_statics: 
 subject: "内閣官房"
 project_id: "jma-project"
 tracker_id: "4"
 filename: "内閣官房.tar"
 description: "内閣官房ファイル"
 content_type: "application/x-tar"


# ------------------------------------------------------------
# XMLの解析を行うためのルールを定義したファイルを指定
# 定義内容が多いため外出しのファイルとする
# ------------------------------------------------------------
jma_rule_file: "config/jma_parse_rule.yml"
ksn_rule_file: "config/ksn_parse_rule.yml"

# ------------------------------------------------------------
# XMLの妥当性チェックを行う際に使用するスキーマファイルへのパス
# ------------------------------------------------------------
schema_file: "schemas/jmx.xsd"

# ------------------------------------------------------------
# 訓練モード時の固定プロジェクトID
# ------------------------------------------------------------
training_project_id: "training-project"

# ------------------------------------------------------------
# 試験モード時の固定プロジェクトID
# ------------------------------------------------------------
test_project_id: "test-project"


